apiVersion: v1
kind: ReplicationController
metadata:
  name: webapp-rc
spec:
  replicas: 3
  selector:
    app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: httpd
        image: httpd
        ports:
        - containerPort: 80
